apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: sql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
      - image: mysql
        name: abc
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1"
        ports:
          - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  type: NodePort
  selector:
    app: sql-pod
  ports:
    - port: 3306
      
